public class MainClass {
    public static void main(String[] args) {
        Lampada L1 = new Lampada();
        L1.cor = "RGB";
        L1.marca = "Xiaomi";
        L1.tipo = "Smart";
        L1.voltagem = 220;
        L1.impDados();
        L1.funcao();
        System.out.println(" ");
        Televisao T1 = new Televisao();
        T1.tela = "OLED";
        T1.marca = "Samsung";
        T1.tipo = "Smart";
        T1.polegadas = 65;
        T1.impDados();
        T1.funcao();
        System.out.println(" ");
        Elevador E1 = new Elevador();
        E1.altura = 2.5;
        E1.largura = 1.5;
        E1.profundidade = 1.5;
        E1.capacidade = 5;
        E1.impDados();
        System.out.println("Selecione o andar");
        E1.funcao();
        System.out.println(" ");
        Cadeira C1 = new Cadeira();
        C1.cor = "Verde e preta";
        C1.marca = "Razer";
        C1.tipo = "Gamer";
        C1.preco = 2500;
        C1.impDados();
        C1.funcao();
        System.out.println(" ");
        Aluno A1 = new Aluno();
        A1.nome = "Paulo Sergio";
        A1.sobrenome= "Oliveira";
        A1.curso = "Informática";
        A1.idade = 16;
        A1.impDados();
        A1.funcao();
        System.out.println(" ");
        Datashow D1 = new Datashow();
        D1.marca = "Epson";
        D1.peso = 2.7;
        D1.voltagem = 220;
        D1.serie = "Powerlite E20";
        D1.impDados();
        D1.funcao();
        System.out.println(" ");
        Microondas M1 = new Microondas();
        M1.marca = "Panasonic";
        M1.capacidade = 21;
        M1.potencia = 700;
        M1.cor = "Branco";
        M1.impDados();
        M1.funcao();
    }
}
